# docker-compose file for 're-demo'
version: "3.9"

networks:
  re-demo-network:
    name: re-demo-network
    driver: bridge

services:
  # re-demo-api
  re-demo-api-svc:
    image: re-demo-api-img:latest
    restart: always
    environment:
      - API_TOKEN=${RE_DEMO_API_TOKEN}
    ports:
      - "0.0.0.0:${RE_DEMO_API_PORT}:80"
    networks:
      - re-demo-network
